'use client';
import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { jarMemories, letters, loveNotes, memories } from '../data/memories';
import { Lily } from '../components/Lily';
import { Petals } from '../components/Petals';
import { Reveal } from '../components/Reveal';

function Heading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <Reveal className="mx-auto max-w-xl text-center"><p className="mb-4 text-[10px] uppercase tracking-[.28em] text-[#9b806b]">{eyebrow}</p><h2 className="serif text-5xl leading-[.9] text-[#465448] sm:text-6xl">{title}</h2>{copy && <p className="mt-6 leading-7 text-[#677168]">{copy}</p>}</Reveal>;
}

function MemoryJar() {
  const [note, setNote] = useState<string>();
  return <section className="bg-[#e8efe4] px-5 py-24 sm:px-6"><Heading eyebrow="A little surprise" title="The memory jar" copy="A small collection of moments, saved for whenever you need one."/><div className="mx-auto mt-12 flex flex-col items-center gap-7"><button onClick={() => setNote(jarMemories[Math.floor(Math.random() * jarMemories.length)])} className="group relative h-56 w-44 rounded-[38%_38%_28%_28%] border border-white/80 bg-white/35 shadow-[inset_0_0_28px_rgba(255,255,255,.8),0_25px_35px_rgba(81,102,80,.15)]"><span className="absolute -top-4 left-7 h-8 w-28 rounded-full border border-[#bdcdb8] bg-[#dbe6d7]"/><Lily className="absolute left-8 top-14 text-[#e8c8bf] transition-transform duration-500 group-hover:rotate-12" size={112}/><span className="absolute bottom-5 inset-x-0 text-[9px] uppercase tracking-[.2em] text-[#84917e]">tap gently</span></button><AnimatePresence>{note && <motion.div key={note} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="glass max-w-sm rounded-sm p-7 text-center"><p className="serif text-2xl italic">“{note}”</p></motion.div>}</AnimatePresence></div></section>;
}

function Letters() {
  const [opened, setOpened] = useState(false); const letter = letters[0];
  return <section className="overflow-hidden bg-[#fcf5ef] px-5 py-24 sm:px-6"><Heading eyebrow="Words to keep" title="Letters, for you" copy="This little desk is always open for more letters."/><div className="envelope mx-auto mt-24 flex min-h-[410px] justify-center"><button onClick={() => setOpened(!opened)} className={`relative h-52 w-72 text-left sm:w-80 ${opened ? 'opened' : ''}`} aria-expanded={opened}><article className="letter absolute left-6 right-6 top-5 z-10 min-h-[220px] rounded-sm bg-[#fffdfa] p-6 shadow-lg"><p className="text-[9px] uppercase tracking-[.18em] text-[#a38b75]">{letter.date}</p><h3 className="serif mt-2 text-2xl">{letter.title}</h3><p className="mt-3 text-xs leading-5 text-[#667066]">{letter.body}</p></article><div className="absolute inset-x-0 bottom-0 z-20 h-44 overflow-hidden rounded-b-md bg-[#eacfc6] shadow-lg"><div className="absolute -left-2 top-0 h-56 w-56 origin-top-left rotate-45 bg-[#f1dcd5]"/><div className="absolute -right-2 top-0 h-56 w-56 origin-top-right -rotate-45 bg-[#efd7cf]"/></div><div className="envelope-flap absolute left-0 top-0 z-30 h-32 w-full overflow-hidden"><div className="h-56 w-56 origin-top-left rotate-45 bg-[#e6c8be]"/></div><span className="absolute -bottom-16 inset-x-0 text-center text-[10px] uppercase tracking-[.2em] text-[#987d69]">{opened ? 'Tap to close' : 'Tap to open'}</span></button></div></section>;
}

export default function Home() {
  const [entered, setEntered] = useState(false);
  return <main className="paper-grain overflow-hidden"><Petals/>
    <section className="relative flex min-h-[100svh] items-center justify-center px-5 sm:px-6"><div className="absolute -left-16 top-20 h-72 w-72 rounded-full bg-[#efd9d2]/45 blur-3xl"/><div className="absolute -right-24 bottom-8 h-96 w-96 rounded-full bg-[#dbe4d7]/55 blur-3xl"/><Reveal className="relative z-10 max-w-2xl text-center"><Lily className="mx-auto mb-8 text-[#d9afa7]"/><p className="mb-6 text-[10px] uppercase tracking-[.3em] text-[#9e846f]">A little date, from Vellore to Mumbai</p><h1 className="serif text-6xl leading-none sm:text-8xl">Hi Aru <span className="text-[#c98e84]">♥</span></h1><p className="mx-auto mt-9 max-w-md whitespace-pre-line text-[15px] leading-8 text-[#657067]">I know things haven&apos;t been easy lately.{`\n\n`}I wish I could be there to hug you.{`\n\n`}Since I can&apos;t...{`\n\n`}I thought I&apos;d bring a few memories to you instead.</p><button onClick={() => { setEntered(true); document.getElementById('memories')?.scrollIntoView({ behavior: 'smooth' }); }} className="mt-10 rounded-full border border-[#cbb29a] bg-white/60 px-7 py-4 text-sm text-[#556154] shadow-sm">Let&apos;s go on another date 🌸</button></Reveal></section>
    <motion.div id="memories" initial={{ opacity: 0 }} animate={{ opacity: entered ? 1 : .72 }}><section className="px-5 py-24 sm:px-6"><Heading eyebrow="A timeline of us" title="Little chapters, kept close" copy="Each stop is ready for you to make it yours."/><div className="relative mx-auto mt-16 max-w-5xl"><div className="timeline-line absolute bottom-8 left-3 top-8 w-px md:left-1/2"/>{memories.map((memory, i) => <Reveal key={memory.title} className={`relative mb-20 ml-8 flex flex-col gap-5 md:mb-28 md:ml-0 md:w-[calc(50%-2.5rem)] ${i % 2 ? 'md:ml-[calc(50%+2.5rem)]' : ''}`}><span className={`absolute top-8 h-3 w-3 rounded-full border-2 border-[#fcfaf5] bg-[#c99688] -left-[29px] md:${i % 2 ? '-left-[47px]' : '-right-[47px]'}`}/><div className="relative aspect-[4/3] overflow-hidden rounded-[1.35rem] bg-transparent">
  <img src={memory.image} alt={memory.title} className="h-full w-full rounded-[1.35rem] object-contain object-center"/>
</div><article className="glass rounded-[1.5rem] p-6"><p className="text-[10px] uppercase tracking-[.2em] text-[#a48870]">{memory.date}</p><h3 className="serif mt-3 text-4xl leading-none">{memory.title}</h3><p className="mt-5 text-sm leading-7 text-[#667166]">{memory.story}</p><p className="serif mt-5 border-l border-[#d6b7ad] pl-4 text-lg italic text-[#788274]">“{memory.quote}”</p></article></Reveal>)}</div></section>
    <section className="bg-[#f6f2ea] px-5 py-24 sm:px-6"><Heading eyebrow="The smallest details" title="Things I love about you"/><div className="mx-auto mt-14 grid max-w-5xl gap-4 sm:grid-cols-2 lg:grid-cols-3">{loveNotes.map((note, i) => <Reveal key={note} delay={i * .07}><article className="glass min-h-36 rounded-[1.5rem] p-7"><Lily className="mb-5 text-[#d8b1a8]" size={35}/><p className="serif text-2xl leading-tight">{note}</p></article></Reveal>)}</div></section><MemoryJar/><Letters/><section className="px-5 py-28 text-center"><Lily className="mx-auto mb-8 text-[#d9afa7]"/><Heading eyebrow="There is so much ahead" title="Our story isn&apos;t finished."/><p className="mt-8 text-sm tracking-[.1em] text-[#748074]">More memories loading<span className="inline-block w-6 animate-pulse">...</span></p></section><footer className="bg-[#405044] px-5 py-24 text-center text-[#f7f1e9]"><p className="serif mx-auto max-w-xl text-4xl leading-tight sm:text-5xl">No matter how many kilometres separate us...<br/>You&apos;ll always have a home in my heart.</p><p className="mt-10 text-2xl text-[#efc8c1]">♥</p><p className="mt-4 text-xs tracking-[.2em] text-[#d6ded4]">— VISHWA</p></footer></motion.div>
  </main>;
}
